### ISSUE TITLE
where can i deploy? 

### ISSUE THREAD

**Issue by cityji** [micl2e2/tg-focus#22]
i think it will work as long as my pc is winning right?
i might need to get the filtered msg asap, even when my computer isn't running .. is it possible oviously yes
but how where? 
i am a student and this is a fun experiment for me so i am in no budget for this, 
i have a free 1 yr amazon aws pack pack though ..

any suggestions?

**Comment by teamlee** [comment]
Hello! 

You are free to deploy tg-focus anywhere, as long as the machine satisfies the deployment requirements and follow the steps introduced by README.

**Comment by micl2e2** [comment]
Hello!

You are free to deploy tg-focus anywhere, as long as the machine satisfies the deployment requirements and one should follow the instructions recommended by README. Additionally, keeping the machine always on is the least requirement for long-term usage.

**Comment by cityji** [comment]
got it, 
i got it running in a raspberry-pi rinning aside  wifi router, 
it's working fine :)
