### ISSUE TITLE
Can't authorize if two-step verification is enabled

### ISSUE THREAD

**Issue by lopatoid** [micl2e2/tg-focus#3]
I'm running tg-focus from Docker image micl2e2/tg-focus version 1.4.1814.
I couldn't log in until I turned off two-step verification in my Telegram account. Error message:
`[tf-focusd] Waiting for authorization`

**Comment by micl2e2** [comment]
Hi!

A bug for current release, and it will be fixed in next minor release(i.e. 1.5.x).
