### ISSUE TITLE
new TG-FOCUS chat created on every application restart

### ISSUE THREAD

**Issue by lopatoid** [micl2e2/tg-focus#4]
I'm not sure if this is a bug, but a new chat "TG-FOCUS" is created every time tg-focus restarts. It's very inconvenient and now I have a lot of identical chats.
![image](https://github.com/micl2e2/tg-focus/assets/1956241/ba27da29-3cb4-4bd1-a520-8ee5ef912525)

**Comment by micl2e2** [comment]
Hi!

This is not a bug, check https://github.com/micl2e2/tg-focus#too-many-tg-focus-chats-created-what-should-i-do for more details.

**Comment by micl2e2** [comment]
Starting from version 1.6, the TG-FOCUS chat group is created across restarts, only if there is none .
