### ISSUE TITLE
[enhancement] Make keywords case insensitive

### ISSUE THREAD

**Issue by lopatoid** [micl2e2/tg-focus#5]
Keywords ["football", "soccer"] not matching "Football" or "SOCCER". Maybe sometimes this is desired, but in most cases not. One can bypass this limitation using regexp (something like ["[fF][oO][oO][tT][bB][aA][lL][lL]"]) but it should be reflected in the documentation.

**Comment by micl2e2** [comment]
There are several places in README that have mentioned about the support of regular expressions. Please check the README file.
